" Tab bar
set showtabline=2

" Status bar
set laststatus=2 statusline=\ Line\ %l,\ Column\ %c%=%{toupper(&fileencoding)}%{repeat(\"\ \",5)}%{toupper(&fileformat)}%{repeat(\"\ \",5)}%{&shiftwidth}%{repeat(\"\ \",4)}\ %Y%{repeat(\"\ \",5)}

" Enable mouse support for terminals
set mouse=a

" Show line numbers
set number

" Enable syntax highlighting
syntax enable
set background=dark " Use "light" for light theme
colorscheme solarized

" Highlight current line
set cursorline

" Don't wrap lines
set nowrap

" Show vertical line at column 80
set colorcolumn=80

" Show whitespaces and tabs
set list listchars=space:·,tab:──

" Insert 4 whitespace characters when the tab key is pressed
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" Copy the indentation from the previous line, when starting a new line
set autoindent

" Fold code based on indentation
set foldmethod=indent foldminlines=0

" Find search term while typing
set incsearch

" Show the current command in the bottom right corner
set showcmd

" List files with builtin filebrowser as tree on the left side and without banner
let g:netrw_liststyle=3
let g:netrw_banner=0
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 20

" Display CtrlP dropdown at the top of the window
let g:ctrlp_match_window = 'top,order:ttb,result:0'

" Show only methods/functions with CtrlPBufTag
let g:ctrlp_buftag_types = {'php': '--php-kinds=f'}

" Custom mapping for multiple cursors
let g:multi_cursor_use_default_mapping = 0
let g:multi_cursor_start_word_key = '<C-d>'
let g:multi_cursor_select_all_word_key = '<A-d>'
let g:multi_cursor_start_key = 'g<C-d>'
let g:multi_cursor_select_all_key = 'g<A-d>'
let g:multi_cursor_next_key = '<C-d>'
let g:multi_cursor_prev_key = '<C-p>'
let g:multi_cursor_skip_key = '<C-x>'
let g:multi_cursor_quit_key = '<Esc>'

" Open new tab with <Ctrl> + t
noremap <C-t> :tabnew<Enter>

" Close tab with <Ctrl> + w
noremap <C-w> :tabclose<Enter>

" Got to function/method definition in file with <Ctrl> + r
noremap <C-r> :CtrlPBufTag<Enter>
